# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: articulate/actions-markdownlint@v1
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies for linting and testing
      run: |
        python -m pip install --upgrade pip
        pip install black pytest ruff
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Lint with black and ruff
      run: |
        ruff .
        black . 
    - name: Install package locally
      run: |
        python -m pip install .
    - name: Test with pytest
      run: |
        pytest
            
